# Generated by Django 2.2.3 on 2019-07-11 19:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sell_api', '0001_initial_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='children',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='sell_api.Category'),
        ),
    ]
