# Generated by Django 2.2.3 on 2019-07-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell_api', '0003_auto_20190711_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent',
            new_name='children',
        ),
    ]
